# Hexo Configuration
# 站点配置文件
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# Site
# 网站标题
title: Amoxicillin-Le’s blog
# 网站副标题
subtitle: 'Let life be beautiful like summer flowers'
# 网站描述 主要用于SEO，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词
description: '日常生活 工作 成长...吧啦吧啦...'
# 网站的关键词。使用半角逗号 , 分隔多个关键词
keywords:
# 作者名字
author: Amoxicillin-Le
# 网站使用的语言，需要去查看主题文件夹内支持的语言
language: zh_CN
# 网站时区。Hexo 默认使用您电脑的时区。请参考 时区列表 进行设置，如 America/New_York, Japan, 和 UTC 。一般的，对于中国大陆地区可以使用Asia/Shanghai。
timezone: 'Asia/Shanghai'

# URL
## 在此处设置您的网站网址。 例如，如果您使用GitHub Page，则将url设置为“ https://username.github.io/project”
url: https://kar98.com.cn/
# 文章的永久链接 默认格式 :year/:month/:day/:title/
permalink: :year/:month/:day/:title/
# 永久链接中各部分的默认值
permalink_defaults:
# 改写 permalink 的值来美化 URL
pretty_urls:
# 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
# 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
# 资源文件夹，这个文件夹用来存放内容。
source_dir: source
# 公共文件夹，这个文件夹用于存放生成的站点文件。
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories
# Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: :lang
# *跳过指定文件的渲染。**匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径
skip_render:

# Writing
# 默认以标题做为文件名称
new_post_name: :title.md # File name of new posts
# 创建一篇新文章或者新的页面时的默认布局
default_layout: post
# 把标题转换为 title case
titlecase: false # Transform title into titlecase

external_link:
  enable: true    # 在新标签中打开链接
  field: site     # 对整个网站（site）生效或仅对文章（post）生效
  exclude: ''     # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0  # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false      # 是否预览草稿
post_asset_folder: true   # 生成文章的时候生成一个同名的资源目录用于存放图片文件
relative_link: false      # 把链接改为与根目录的相对位址
future: true              # 显示未来的文章
highlight:                # 代码块的设置, see [Highlight.js](https://hexo.io/docs/syntax-highlight#Highlight-js) section for usage guide
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:                  # #代码块的设置, see [PrismJS](https://hexo.io/docs/syntax-highlight#PrismJS) section for usage guides
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Amoxicillin-Le/Amoxicillin-Le.GitHub.io
  branch: main
  token: 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

# Docs: https://github.com/hexojs/hexo-renderer-markdown-it
markdown:
  preset: 'commonmark'
  render:
    html: true                        # 定义文档中的HTML内容是否应转义或传递给最终结果
    xhtmlOut: false                   # 定义解析器是否将导出完全兼容XHTML的标记
    langPrefix: 'language-'
    breaks: true                      # 使源文件中的换行符被解析为<br>标记。每次按Enter键都会创建换行符
    linkify: true                     # 解析器能够将直接粘贴到文本中的链接内联
    typographer: true                 # 可以替换常见的排版元素
    quotes: '“”‘’'                    # 单引号、双引号如何被替换
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
    - markdown-it-imsize
    - markdown-it-mark
    - markdown-it-regexp
    - markdown-it-task-checkbox
    - markdown-it-expandable
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: info
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
    - name: markdown-it-container
      options: tips
    - markdown-it-deflist
    - name: markdown-it-emoji
      options:
        shortcuts: {}
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'